/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kirrupt_pdfiumandroid_PDFReader */

#ifndef _Included_com_kirrupt_pdfiumandroid_PDFReader
#define _Included_com_kirrupt_pdfiumandroid_PDFReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kirrupt_pdfiumandroid_PDFReader
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kirrupt_pdfiumandroid_PDFReader_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFReader
 * Method:    loadLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kirrupt_pdfiumandroid_PDFReader_loadLibrary
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFReader
 * Method:    destroyLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kirrupt_pdfiumandroid_PDFReader_destroyLibrary
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
