/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kirrupt_pdfiumandroid_PDFDocument */

#ifndef _Included_com_kirrupt_pdfiumandroid_PDFDocument
#define _Included_com_kirrupt_pdfiumandroid_PDFDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    LoadDocument
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_LoadDocument
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    LoadPage
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_LoadPage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    RenderPage
 * Signature: (IIII)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_RenderPage
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    getBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_getBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    getBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_getBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    getBufferWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_getBufferWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    getBufferHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_getBufferHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    getBufferStride
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_getBufferStride
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    getJavaBitmap
 * Signature: (Landroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_getJavaBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    getRectangleBitmapSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_getRectangleBitmapSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    renderRectangleWithScale
 * Signature: (IIFIILandroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_renderRectangleWithScale
  (JNIEnv *, jobject, jint, jint, jfloat, jint, jint, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    renderRectangle
 * Signature: (IIIIIILandroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_renderRectangle
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    destroyBitmap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_destroyBitmap
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    width
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_width
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    height
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_height
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    closePage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_closePage
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    closeDocument
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_closeDocument
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    getPageObjects
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_getPageObjects
  (JNIEnv *, jobject);

/*
 * Class:     com_kirrupt_pdfiumandroid_PDFDocument
 * Method:    getPageObjectsSmart
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_kirrupt_pdfiumandroid_PDFDocument_getPageObjectsSmart
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
